<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue</name>
   <tag></tag>
   <elementGuidId>61b98719-52a4-4d3f-a260-0a41c9be157d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' border-t ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.border-t</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb7c6620-dfea-4c7d-a5e6-19acd5f00522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sticky bottom-0 z-50 border-t bg-background px-4 py-4</value>
      <webElementGuid>cc15f647-7b29-4441-9772-fdd312c1d4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>624322e4-e18c-47ea-a13e-92e011b29316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ef97c4fb4d2d740c6606d6b64e1b46d0</value>
      <webElementGuid>75b55c02-bb55-4c01-9f8d-b444cee2d0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' border-t ')]</value>
      <webElementGuid>95b9285a-fbee-4ee7-b514-72e150f22107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' border-t ')]</value>
      <webElementGuid>4bad2727-6799-4afa-af11-26723af7ab9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>1b064ffe-722c-4152-af29-39ed6c0c34fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
