<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Login button on login page</description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>admin-login-btn-001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid='btn-login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid='btn-login']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid='btn-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>admin-login-btn-guid</webElementGuid>
   </webElementProperties>
</WebElementEntity>
