<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Email input field on login page</description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>admin-login-email-001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid='input-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid='input-email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid='input-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>admin-email-input-guid</webElementGuid>
   </webElementProperties>
</WebElementEntity>
