<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Password input field on login form</description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>c3d4e5f6-a7b8-4c5d-0e1f-2a3b4c5d6e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-testid='input-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-testid='input-password']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid='input-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-password</value>
      <webElementGuid>c3d4e5f6-a7b8-4c5d-0e1f-2a3b4c5d6e7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
